export const API_ENDPOINTS = {
  REGISTER_USER: '/v1/admin/register-user',
  LOGIN_ADMIN: '/v1/admin/login-admin',
  GET_ADMIN: '/v1/admin/admin-profile',
  GET_USER_BY_ID: '/v1/admin/getById/',

  // FORGOT_PASSWORD_USER:'/v1/forgot-password',
  // RESET_PASSWORD_USER:'/v1/reset-password',
  UPDATE_BY_Id: '/v1/admin/update/',
  GET_ALL_USERS: '/v1/admin/allUsers/',
  DELETE_BY_ID: '/v1/admin/delete/',
  EXPORT_USER: '/v1/admin/exportUser',
  EXPORT_SINGLE_USER: '/v1/admin/exportSingleUser/',
  GET_ALL_POST: '/v1/post/allPosts',
  CREATE_POST: '/v1/post/create-post',

  // GET_MY_POST:'/v1/post/mypost/posts',
  GET_POST_BY_ID: '/v1/post/getById/',
  DELETE_POST_BY_ID: '/v1/post/delete/',
  UPDATE_POST_BY_ID: '/v1/post/update/',
  EXPORT_POST: '/v1/post/exportPost',
  EXPORT_SINGLE_POST: '/v1/post/exportSinglePost/',

  SUMMARY: '/v1/dashboard/summary',
  TOP_CATEGORIES: '/v1/dashboard/topCategories',
  TOP_CONTRIBUTORS: '/v1/dashboard/topContributors',
  RECENT_USER_ACTIONS: '/v1/dashboard/userActions',
  RECENT_POST_ACTIONS: '/v1/dashboard/postActivities',
  USER_POST_CORRELATION: '/v1/dashboard/userPostCorrelation',
  SIGNUPS_BY_COUNTRY: '/v1/dashboard/signupsByCountry',
}
