export const  SUMMARY= 'SUMMARY';
export const  TOP_CATEGORIES= 'TOP_CATEGORIES';
export const  TOP_CONTRIBUTORS= 'TOP_CONTRIBUTORS';
export const RECENT_USER_ACTIONS= 'RECENT_USER_ACTIONS';
export const  RECENT_POST_ACTIONS= 'RECENT_POST_ACTIONS';
export const  USER_POST_CORRELATION= 'USER_POST_CORRELATION';
export const  SIGNUPS_BY_COUNTRY= 'SIGNUPS_BY_COUNTRY';