// src/utils/countryData.js
import { Country, State } from 'country-state-city';

// Get all countries
export const getCountries = () => {
  return Country.getAllCountries().map(country => ({
    name: country.name,
    isoCode: country.isoCode
  }));
};

// Get states by country ISO code
export const getStatesByCountry = (countryCode) => {
  return State.getStatesOfCountry(countryCode).map(state => ({
    name: state.name,
    isoCode: state.isoCode
  }));
};

export const languageData =  ["English", "Spanish", "French", "German", "Chinese", "Hindi", "Arabic", "Portuguese", "Russian","Japanese","Korean",
  "Italian", "Dutch", "Turkish", "Polish", "Swedish", "Norwegian", "Finnish", "Greek", "Hebrew", "Thai", "Vietnamese", "Indonesian", "Bengali",
  "Tamil", "Telugu", "Malay", "Urdu"];

export const currencyList = [
  "AED (د.إ)",
  "AFN (؋)",
  "ALL (L)",
  "AMD (֏)",
  "ANG (ƒ)",
  "AOA (Kz)",
  "ARS ($)",
  "AUD (A$)",
  "AWG (ƒ)",
  "AZN (₼)",
  "BAM (KM)",
  "BBD ($)",
  "BDT (৳)",
  "BGN (лв)",
  "BHD (.د.ب)",
  "BIF (FBu)",
  "BMD ($)",
  "BND (B$)",
  "BOB (Bs.)",
  "BRL (R$)",
  "BSD ($)",
  "BTN (Nu.)",
  "BWP (P)",
  "BYN (Br)",
  "BZD (BZ$)",
  "CAD (C$)",
  "CDF (FC)",
  "CHF (CHF)",
  "CLP ($)",
  "CNY (¥)",
  "COP ($)",
  "CRC (₡)",
  "CUP ($)",
  "CVE ($)",
  "CZK (Kč)",
  "DJF (Fdj)",
  "DKK (kr)",
  "DOP (RD$)",
  "DZD (دج)",
  "EGP (£)",
  "ERN (Nfk)",
  "ETB (Br)",
  "EUR (€)",
  "FJD (FJ$)",
  "FKP (£)",
  "FOK (kr)",
  "GBP (£)",
  "GEL (₾)",
  "GGP (£)",
  "GHS (₵)",
  "GIP (£)",
  "GMD (D)",
  "GNF (FG)",
  "GTQ (Q)",
  "GYD ($)",
  "HKD (HK$)",
  "HNL (L)",
  "HRK (kn)",
  "HTG (G)",
  "HUF (Ft)",
  "IDR (Rp)",
  "ILS (₪)",
  "IMP (£)",
  "INR (₹)",
  "IQD (ع.د)",
  "IRR (﷼)",
  "ISK (kr)",
  "JEP (£)",
  "JMD (J$)",
  "JOD (د.ا)",
  "JPY (¥)",
  "KES (Sh)",
  "KGS (сом)",
  "KHR (៛)",
  "KID (A$)",
  "KMF (CF)",
  "KRW (₩)",
  "KWD (د.ك)",
  "KYD ($)",
  "KZT (₸)",
  "LAK (₭)",
  "LBP (ل.ل)",
  "LKR (Rs)",
  "LRD ($)",
  "LSL (L)",
  "LYD (ل.د)",
  "MAD (د.م.)",
  "MDL (L)",
  "MGA (Ar)",
  "MKD (ден)",
  "MMK (Ks)",
  "MNT (₮)",
  "MOP (P)",
  "MRU (UM)",
  "MUR (₨)",
  "MVR (Rf)",
  "MWK (MK)",
  "MXN (Mex$)",
  "MYR (RM)",
  "MZN (MT)",
  "NAD ($)",
  "NGN (₦)",
  "NIO (C$)",
  "NOK (kr)",
  "NPR (₨)",
  "NZD (NZ$)",
  "OMR (ر.ع.)",
  "PAB (B/.)",
  "PEN (S/.)",
  "PGK (K)",
  "PHP (₱)",
  "PKR (₨)",
  "PLN (zł)",
  "PYG (₲)",
  "QAR (ر.ق)",
  "RON (lei)",
  "RSD (дин)",
  "RUB (₽)",
  "RWF (FRw)",
  "SAR (ر.س)",
  "SBD ($)",
  "SCR (₨)",
  "SDG (£)",
  "SEK (kr)",
  "SGD (S$)",
  "SHP (£)",
  "SLE (Le)",
  "SLL (Le)",
  "SOS (Sh)",
  "SRD ($)",
  "SSP (£)",
  "STN (Db)",
  "SYP (£)",
  "SZL (L)",
  "THB (฿)",
  "TJS (ЅМ)",
  "TMT (m)",
  "TND (د.ت)",
  "TOP (T$)",
  "TRY (₺)",
  "TTD (TT$)",
  "TVD (A$)",
  "TWD (NT$)",
  "TZS (Sh)",
  "UAH (₴)",
  "UGX (Sh)",
  "USD ($)",
  "UYU ($U)",
  "UZS (сўм)",
  "VES (Bs.)",
  "VND (₫)",
  "VUV (Vt)",
  "WST (T)",
  "XAF (FCFA)",
  "XCD (EC$)",
  "XOF (CFA)",
  "XPF (₣)",
  "YER (﷼)",
  "ZAR (R)",
  "ZMW (ZK)",
  "ZWL (Z$)"
];
